Add support for themes
jekyll/directory pull request #33
Opened 2017-01-18 00:08 UTC by DirtyF

![jekyll-directory](https://cloud.githubusercontent.com/assets/103008/22045427/74f8ca4c-dd1a-11e6-8572-bc261d0fd16a.png)

2017-02-02 00:21 UTC, pathawks approved these changes
:heart:

2017-02-02 15:14 UTC, pathawks requested changes

2017-02-02 15:14 UTC, pathawks commented on _config.yml
> +baseurl: /directory
This seems to have broken everything.

Do we need to rename the repository at the same time we make this change?

2017-02-03 18:05 UTC, DirtyF commented
@jekyll/plugin-core added only Github Pages for now, will add some gem-based themes later.

2017-02-11 21:30 UTC, parkr commented on _config.yml
> +baseurl: /directory
I would let GitHub Pages do this for you automatically: https://github.com/jekyll/github-metadata/blob/8906f2b9c890f0aafef96423c7cd7e5047f7dae4/lib/jekyll-github-metadata/ghp_metadata_generator.rb#L36-L45

2017-02-11 21:32 UTC, parkr commented on _config.yml
> +      type: rubygems              # DO NOT CHANGE THIS DEFAULT
Idea: let's have a test spec that explicitly checks that the individual themes (and plugins above) abide by these conventions unless explicitly overridden in the case of `type` only.

2017-04-12 14:02 UTC, DirtyF commented
Preview on Github Pages on my repo: https://dirtyf.github.io/directory/

2018-01-08 16:59 UTC, parkr approved these changes
This diff is way too huge to review so merge once you think it's ready! We can always iterate 😄

2018-01-08 17:16 UTC, merged